<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\OFG.Host.Module\OFG.Host.Module.csproj"/>
        <ProjectReference Include="..\OGF.Module.Authentication.Contracts\OGF.Module.Authentication.Contracts.csproj"/>
        <ProjectReference Include="..\OGF.Module.Authentication.Plugin\OGF.Module.Authentication.Plugin.csproj"/>
        <ProjectReference Include="..\OGF.Module.Authentication.Plugin.Default\OGF.Module.Authentication.Plugin.Default.csproj" Private="true"/>
    </ItemGroup>


</Project>
